name: RPGItems
version: 1.0.0
main: Moon2.rPGWeapon.Main
api-version: 1.16
authors:
  - Mooooonrabbbit
  - WN_Mr_chen
description: 添加自定义武器

commands:
  heatblade:
    description: 获取炽热之剑
    usage: /heatblade
  corruptedtrident:
    description: 获取腐蚀的三叉戟
    usage: /corruptedtrident
  rocketboots:
    description: 获取火箭靴
    usage: /rocketboot
  weightlessbow:
    description: 获取无重力长弓
    usage: /weightlessbow
  dicesword:
    description: 获取骰子大剑
    usage: /dicesword